### Post create appointment
POST {{host}}/appointments
Content-Type: application/json

{
  "appointmentTime": "2024-07-01T10:00:00",
  "patientId": 1,
  "doctorId": 2,
  "reason": "Regular check-up"
}

### Reassign appointment to another doctor
PUT {{host}}/api/appointments/5
Content-Type: application/json

{
  "doctorId": 3
}


### Get all appointments for a specific doctor
GET {{host}}/api/appointments/doctor/2?page=0&size=10


### Get all appointments for a specific patient
GET {{host}}/api/appointments/patient/1?page=0&size=10